#!\Users\himanshu\AppData\Local\Programs\Python\Python36-32\python.exe
print('content-type:text/html\r\n\n')
import webbrowser
print('<html>')
print('<head>')
print('</head>')
print('<body style="margin:0;">')
print('<div style="width:100%;background-color:lightblue;height:20%;font-size:50;">')
print('<marquee behavior="alternate" scrollamount="10" vspace="5%" hspace="15%" >',"REGISTRATION FORM",'</marquee>')
print('</div>')
print('<div style="background-color:RGB(13,105,140);width:100%;height:65%">')
print('<form method="post">')
print('<table width="100%" height="90%" align="center">')
print('<br>')
print('<caption > ','<u>','APP REGISTRATION','</u>','</caption>')
print('<tr>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">')
print('<input type="submit" name="Back" value="Back" style="height:10%;width:90%;font-size:20px;">')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td>')
print('Name')
print('</td>')
print('<td>')
print('<input type="text" name="name">')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">',' ')
print('</td>')
print('<td rowspan="9">')
print('<input type="submit" name="submit" value="SIGNUP" style="height:10%;width:90%;font-size:20px;">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Username')
print('</td>')
print('<td>')
print('<input type="text" name="username">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Password')
print('</td>')
print('<td>')
print('<input type="text" name="password">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Confirm Password')
print('</td>')
print('<td>')
print('<input type="text" name="cf">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Email-id')
print('</td>')
print('<td>')
print('<input type="text" name="email">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Mobile No')
print('</td>')
print('<td>')
print('<input type="text" name="no">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Gender')
print('</td>')
print('<td>')
print('<input type="radio" name="Gender" value="Male">Male')
print('<input type="radio" name="Gender" value="Female">Female')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('Address')
print('</td>')
print('<td>')
print('<input type="text"  name="Add">')
print('</td>')
print('</tr>')
print('<tr>')
print('<td>')
print('State')
print('</td>')
print('<td>')
print("""
<select name=slist>
<option value="">------------Select State------------</option>
<option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
<option value="Andhra Pradesh">Andhra Pradesh</option>
<option value="Arunachal Pradesh">Arunachal Pradesh</option>
<option value="Assam">Assam</option>
<option value="Bihar">Bihar</option>
<option value="Chandigarh">Chandigarh</option>
<option value="Chhattisgarh">Chhattisgarh</option>
<option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
<option value="Daman and Diu">Daman and Diu</option>
<option value="Delhi">Delhi</option>
<option value="Goa">Goa</option>
<option value="Gujarat">Gujarat</option>
<option value="Haryana">Haryana</option>
<option value="Himachal Pradesh">Himachal Pradesh</option>
<option value="Jammu and Kashmir">Jammu and Kashmir</option>
<option value="Jharkhand">Jharkhand</option>
<option value="Karnataka">Karnataka</option>
<option value="Kerala">Kerala</option>
<option value="Lakshadweep">Lakshadweep</option>
<option value="Madhya Pradesh">Madhya Pradesh</option>
<option value="Maharashtra">Maharashtra</option>
<option value="Manipur">Manipur</option>
<option value="Meghalaya">Meghalaya</option>
<option value="Mizoram">Mizoram</option>
<option value="Nagaland">Nagaland</option>
<option value="Orissa">Orissa</option>
<option value="Pondicherry">Pondicherry</option>
<option value="Punjab">Punjab</option>
<option value="Rajasthan">Rajasthan</option>
<option value="Sikkim">Sikkim</option>
<option value="Tamil Nadu">Tamil Nadu</option>
<option value="Tripura">Tripura</option>
<option value="Uttaranchal">Uttaranchal</option>
<option value="Uttar Pradesh">Uttar Pradesh</option>
<option value="West Bengal">West Bengal</option>
</select>""")
print('</td>')
print('</tr>')
print('</table>')
print('</div>')
print('<div style="width:100%;background-color:lightblue;height:15%;font-size:20;">')
print('<marquee behavior="left" scrollamount="10" vspace="2%" hspace="5%" >','Please be aware that this Registration Form, when completed, along with the Guide and the Declaration of Acceptance, is your contract with Snapstore and that in signing you are agreeing to the terms and conditions listed below','</marquee>')
print('</div>')
print('</form>')
print('</div>')
import cgi,cgitb
form=cgi.FieldStorage()
if(form.getvalue("submit")):
    name=form.getvalue("name")
    username=form.getvalue("username")
    password=form.getvalue("password")
    cfpassword=form.getvalue("cf")
    email=form.getvalue("email")
    mobile=int(form.getvalue("no"))
    gender=form.getvalue('Gender')
    add=form.getvalue('Add')
    state=form.getvalue("slist")
    import MySQLdb
    db=MySQLdb.connect("localhost","root","root","class" )
    cur=db.cursor()
    try:
        sql="INSERT INTO data(name,user_name,password,confirm_pass,email_id,mobile_num,gender,state,address)VALUES(%s,%s,%s,%s,%s,'%s',%s,%s,%s)"
        cur.execute(sql,[name,username,password,cfpassword,email,mobile,gender,state,add])
        db.commit()
    except:
        db.rollback()
    finally:
        db.close()
        webbrowser.open('http://localhost/Project/login.py') 
elif(form.getvalue("Back")):
    webbrowser.open('http://localhost/Project/login.py')
else:
    ("print some problem")
print('</body>')
print('</html>')

